version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    restart: always
    volumes:
      - .:/app
    ports:
      - "${DJANGO_PORT}:${DJANGO_PORT}"

  nginx:
    build:
      context: ./Docker/nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - .:/app
      - ./Docker/nginx/config/nginx.conf:/etc/nginx/conf.d/nginx.conf:ro
    networks:
      - mynetwork
    depends_on:
      - web
    restart: always

networks:
  mynetwork:
