version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    restart: always
    volumes:
      - .:/app
    ports:
      - "${DJANGO_PORT}:8000"
    networks:
      - app_network

  nginx:
    build:
      context: ./Docker/nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web  # Гарантирует, что NGINX подождет готовности сервиса web
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
