version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    restart: always
    volumes:
      - .:/app
      - static_volume:/app/fedor_recipe_book/static
      - media_volume:/app/fedor_recipe_book/media
    ports:
      - "${DJANGO_PORT}:8000"
    networks:
      - app_network

  nginx:
    build:
      context: ./Docker/nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/fedor_recipe_book/static
      - media_volume:/app/fedor_recipe_book/media
    depends_on:
      - web
    networks:
      - app_network

volumes:
  static_volume:
    driver: local
  media_volume:
    driver: local

networks:
  app_network:
    driver: bridge