version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    restart: always
    volumes:
      - .:/app
    ports:
      - "${DJANGO_PORT}:${DJANGO_PORT}"
#    depends_on:
#      - db
#    restart: always
#
#  db:
#    image: mysql:latest
#    env_file: .env
#    volumes:
#      - mysql_data:/var/lib/mysql
#    environment:
#      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
#
#  nginx:
#    build:
#      context: ./Docker/nginx
#      dockerfile: Dockerfile
#    ports:
#      - "80:80"
#    volumes:
#      - .:/app
#      - ./Docker/nginx/config/nginx.conf:/etc/nginx/conf.d/nginx.conf:ro
#    depends_on:
#      - web
#    restart: always
volumes:
  mysql_data:
