version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    restart: always
    ports:
      - 8000:8000
    volumes:
      - .:/app
  nginx:
    build: 
      context: ./Docker/nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
      - "443:443"
    volumes:
      - ./Docker/nginx/:/etc/nginx/conf.d/
    networks:
      - app_network
networks:
  app_network:
    driver: bridge

volumes:
  nginx_certs: