version: '3'

services:
  web:
    build:
      dockerfile: .
    env_file: .env
    volumes:
      - .:/app
    ports:
      - "${DJANGO_PORT}:${DJANGO_PORT}"
    depends_on:
      - db

  db:
    image: mysql:latest
    env_file: .env
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}

  nginx:
    build:
      context: ./Docker/nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - .:/app
      - ./Docker/nginx/config/nginx.conf:/etc/nginx/conf.d/nginx.conf:ro
    depends_on:
      - web

volumes:
  mysql_data:
