version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    restart: always
    volumes:
      - .:/app
    ports:
      - "${DJANGO_PORT}:${DJANGO_PORT}"

  nginx:
    build:
      context: ./Docker/nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - web
    restart: always

volumes:
  mysql_data:
