# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY fedor_recipe_book/. /app/.

# Install any needed packages specified in requirements.txt
RUN pip install --upgrade pip && pip install -r requirements.txt
# Install any needed packages specified in requirements.txt
RUN pip install -r requirements.txt

# Expose the port on which the Django app will run
ARG DJANGO_PORT
EXPOSE $DJANGO_PORT

# Define the command to run the Django application
CMD ["python", "manage.py", "runserver", "0.0.0.0:$DJANGO_PORT"]
