# Use an official Python runtime as a parent image
FROM python:3.10-slim

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set the working directory in the container
WORKDIR /app
# Copy the current directory contents into the container at /app
COPY . .

# COPY requirements.txt /app/.
# Install any needed packages specified in requirements.txt

RUN apt-get update && apt-get install -y pkg-config
RUN apt-get install -y python3 python3-pip python3-venv libmariadb-dev-compat gcc && \
    rm -rf /var/lib/apt/lists/*
RUN python -m venv .venv
RUN python3 -m pip install --upgrade pip && pip install -r requirements.txt

# Expose the port on which the Django app will run
ARG DJANGO_PORT
EXPOSE $DJANGO_PORT

# Define the command to run the Django application
CMD ["python3", "/app/manage.py", "runserver", "0.0.0.0:8000"]
