version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    restart: always
    volumes:
      - .:/app
    ports:
      - "8000:8000"
  nginx:
    build: 
      context: ./Docker/nginx
      dockerfile: Dockerfile
    ports:
      - ${DOCKER_HTTP_BIND:-8000}:80
      - "443:443"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/
    networks:
      - app_network
networks:
  app_network:
    driver: bridge

volumes:
  nginx_certs: