version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    restart: always
    volumes:
      - .:/app
    ports:
      - "${DJANGO_PORT}:${DJANGO_PORT}"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./fedor_recipe_book/static:/usr/share/nginx/html
    depends_on:
      - web
