# Use an official NGINX image as a parent image
FROM nginx:1.19-alpine


RUN mkdir -p /etc/nginx/conf.d

# Копируем файл конфигурации внутрь контейнера---<<<
COPY default.conf /etc/nginx/conf.d/default.conf

