# Use an official NGINX image as a parent image
FROM nginx:latest

# Remove the default NGINX configuration file
RUN rm /etc/nginx/conf.d/default.conf

# Copy the custom NGINX configuration file to the container
COPY ./nginx.conf /etc/nginx/conf.d/default.conf

# Expose ports
EXPOSE 80

# Command to start NGINX
CMD ["nginx", "-g", "daemon off;"]
