# Use an official NGINX image as a parent image
FROM nginx:1.19-alpine


# Define the custom NGINX configuration directly within the Dockerfile
RUN echo 'server {
    listen       80;
    listen  [::]:80;
    server_name  localhost;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
    }

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}' > /etc/nginx/conf.d/default.conf
