# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Установка необходимых пакетов для pkg-config
# Установка библиотеки libmysqlclient-dev для компиляции mysqlclient
RUN apt-get update && apt-get install -y libmysqlclient-dev
RUN apt-get update && apt-get install -y \
    pkg-config \
 && rm -rf /var/lib/apt/lists/*
 RUN apt-get update && apt-get install -y default-libmysqlclient-dev

RUN python3 -m pip install --upgrade pip
RUN pip install -r requirements.txt

# Expose the port on which the Django app will run
ARG DJANGO_PORT
EXPOSE $DJANGO_PORT

# Define the command to run the Django application
CMD ["python", "manage.py", "runserver", "0.0.0.0:$DJANGO_PORT"]
