# Используем базовый образ Python
FROM python:3.9

# Устанавливаем переменную окружения PYTHONUNBUFFERED на значение 1
# Это предотвращает создание файлов .pyc (кэш-файлов Python) и гарантирует вывод логов в реальном времени
ENV PYTHONUNBUFFERED 1

# Устанавливаем рабочую директорию в /app
WORKDIR /app

# Копируем файл requirements.txt в рабочую директорию контейнера
COPY requirements.txt /app/

# Устанавливаем зависимости, необходимые для проекта Django
RUN pip install -r requirements.txt

# Копируем все файлы проекта Django в рабочую директорию контейнера
COPY . /app/

# Команда CMD выполняется при запуске контейнера
# В данном случае, она запускает сервер Django
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
